import Head from "next/head";

import Image from "next/image";

// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  items-center mx-20 mt-10">
        {/* logo */}
        <div className="font-bold text-green-800 flex-grow">@SkillSay</div>
        <div className="flex text-gray-400">
          <div className=" px-5">programs</div>
          <div className="px-5">For Business</div>
          <div className="px-5">SkillSayAi</div>
          <div className="px-5">Job Board</div>
          <div className="px-5">Our Story</div>
          <div className="px-5">Sign In</div>
        </div>
      </div>
      <div>
        <div className="mt-3">
          <h1 className="uppercase font-medium text-lg text-center text-gray-600 py-3">
            assessment courses
          </h1>
          <div className="grid sm:grid-cols-3 md:grid-cols-4 gap-10 px-20 text-white">
            <div className="border rounded border-green-700 bg-opacity-5 h-[242px] p-5 bg-green-500 shadow-md">
              <p className="text-green-700 text-sm py-3 font-bold">
                Data Interpretation
              </p>
              <p className="text-green-800 text-xs py-3">
                Soft Skills Assesment aimed at validating etc
              </p>
              <div className="rounded-md  bg-green-700 mt-2 w-[70%]">
                <p className="text-center px-3 py-2 ">Take the assessment</p>
              </div>
            </div>

            <div className="border rounded border-green-700 bg-opacity-5 h-[242px] p-5 bg-green-500 shadow-md">
              <p className="text-green-700 text-sm py-3 font-bold">
                Data Interpretation
              </p>
              <p className="text-green-800 text-xs py-3">
                Soft Skills Assesment aimed at validating etc
              </p>
              <div className="rounded-md  bg-green-700 mt-2 w-[70%]">
                <p className="text-center px-3 py-2">Take the assessment</p>
              </div>
            </div>

            <div className="border rounded border-green-700 bg-opacity-5 h-[242px] p-5 bg-green-500 shadow-md">
              <p className="text-green-700 text-sm py-3 font-bold">
                Data Interpretation
              </p>
              <p className="text-green-800 text-xs py-3">
                Soft Skills Assesment aimed at validating etc
              </p>
              <div className="rounded-md  bg-green-700 mt-2 w-[70%]">
                <p className="text-center px-3 py-2">Take the assessment</p>
              </div>
            </div>

            <div className="border rounded border-green-700 bg-opacity-5 h-[242px] p-5 bg-green-500 shadow-md">
              <p className="text-green-700 text-sm py-3 font-bold">
                Data Interpretation
              </p>
              <p className="text-green-800 text-xs py-3">
                Soft Skills Assesment aimed at validating etc
              </p>
              <div className="rounded-md  bg-green-700 mt-2 w-[70%]">
                <p className="text-center px-3 py-2">Take the assessment</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
