import Head from "next/head";

import Image from "next/image";
import { ChevronDownIcon } from "@heroicons/react/outline";
import {} from "@heroicons/react/outline";
import Header from "../components/Header";
import FirstTitle from "../components/FirstTitle";
import CrButton from "../components/CrButton";
import Card from "../components/Card";
import Footer from "../components/Footer";
import LastTitle from "../components/LastTitle";

// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Skill Say</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-10 px-3 sm:px-5 md:px-10">
        {/* header part */}
        <Header />

        {/* section title */}
        <FirstTitle />

        {/* courses button part */}
        <CrButton />

        {/* card section */}
        <div>
          <div className="grid-layout place-items-center px-0 sm:px-20 ">
            {/* card  start*/}

            <Card title="Data Interpretation" />
            <Card title="Python" buttonColor="#3CC13B" />
            <Card title="Data Analytics" />
            <Card title="Data Interpretation" />
            <Card title="Data Interpretation" />

            {/* card  end*/}
          </div>
        </div>
        {/* Title section */}
        <LastTitle />
        {/* footer part  */}
        <Footer />
      </div>
    </div>
  );
}
